import {
  LayoutDashboard,
  UserRoundPen,
  Settings,
  Building2,
  FolderKanban,
  ListOrdered,
  BookOpen,
  BellRing,
  FileStack,
  CreditCard,
  Globe,
  ScrollText,
  AlertOctagon,
  MessageSquareText,
  ShieldAlert,
  UsersRound,
  BarChart3,
  FileSearch,
  TrendingUp,
  Construction,
  History,
  FolderOpen,
  Receipt,
  ShieldCheck,
  MessageCircleQuestion,
  Bell,
  ListChecks,
  Camera,
  AlertTriangle,
  MessageCircle,
  FileText,
  Wrench,
} from "lucide-react";

export const icons = {
  LayoutDashboard,
  UserRoundPen,
  Settings,
  Building2,
  FolderKanban,
  ListOrdered,
  BookOpen,
  BellRing,
  FileStack,
  CreditCard,
  Globe,
  ScrollText,
  AlertOctagon,
  MessageSquareText,
  ShieldAlert,
  UsersRound,
  BarChart3,
  FileSearch,
  TrendingUp,
  Construction,
  History,
  FolderOpen,
  Receipt,
  ShieldCheck,
  MessageCircleQuestion,
  Bell,
  ListChecks,
  Camera,
  AlertTriangle,
  MessageCircle,
  FileText,
  Wrench,
} as const;

export type IconName = keyof typeof icons;